version: 1.0.0-{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: 24
    - RUBY_VERSION: 23
    - RUBY_VERSION: 22
    - RUBY_VERSION: 21

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
    # appveyor does not seem to have a way to cleanup the env and does not actually start from scratch each time
  - gem uninstall bundler --executables || true
  - gem install bundler -v 1.7
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
